config/routes.rb
CookbookApp::Application.routes.draw do
  root :to => 'home#index'
  resources :cookbooks
  resources :recipes
  resources :ingredients
end

app/models/cookbook.rb
# == Schema Information
#
# Table name: cookbooks
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  cuisine     :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  isbn        :integer
#

class Cookbook < ActiveRecord::Base
  attr_accessible :cuisine, :description, :title, :isbn, :recipe_ids

  has_many :recipes, inverse_of: :cookbook
  has_many :ingredients, through: :recipes

  validates_uniqueness_of :title, :isbn


end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :measurement, :name, :recipe_ids

  has_and_belongs_to_many :recipes
  has_many :cookbooks, through: :recipes

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  instructions :text
#  name         :string(255)
#  serving_size :integer
#  img_url      :text
#  course       :string(255)
#  cook_time    :integer
#  cookbook_id  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :cook_time, :course, :img_url, :instructions, :name, :serving_size, :cookbook_id

  belongs_to :cookbook, inverse_of: :recipes
  has_and_belongs_to_many :ingredients


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  def index
    @cookbooks = Cookbook.all
  end
  def create
    cookbook = Cookbook.new(params[:cookbook])
    if cookbook.save
      redirect_to cookbooks_path
    else
      redirect_to new_cookbook_path
    end
  end

  def new
    @cookbook = Cookbook.new
    @recipes = Recipe.all
  end

  def edit
    @cookbook = Cookbook.find(params[:id])
    @recipes = Recipe.all
  end

  def show
    @cookbook = Cookbook.find(params[:id])
  end

  def update
    binding.pry
    cookbook = Cookbook.find(params[:id])
    if cookbook.update_attributes(params[:cookbook])
      redirect_to cookbooks_path
    else
      redirect_to edit_cookbook_path
    end
  end

  def destroy
    Cookbook.find(params[:id]).delete
    redirect_to cookbooks_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def create
    ingredient = Ingredient.new(params[:ingredient])
    if ingredient.save
      redirect_to ingredients_path
    else
      redirect_to new_ingredient_path
      # render :new
    end
  end

  def new
    @ingredient = Ingredient.new
    @recipes = Recipe.all
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
    @recipes = Recipe.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    ingredient = Ingredient.find(params[:id])
    if ingredient.update_attributes(params[:ingredient])
      redirect_to ingredients_path
    else
      redirect_to edit_ingredient_path
    end
  end

  def destroy
    Ingredient.find(params[:id]).delete
    redirect_to ingredients_path
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def create
    recipe = Recipe.new(params[:recipe])
    if recipe.save
      redirect_to recipes_path
    else
      redirect_to new_recipe_path
      # render :new
    end
  end

  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @ingredients = Ingredient.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def update
    recipe = Recipe.find(params[:id])
    if recipe.update_attributes(params[:recipe])
      redirect_to recipes_path
    else
      redirect_to edit_recipe_path
    end
  end

  def destroy
    Recipe.find(params[:id]).delete
    redirect_to recipes_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookbooks/edit.html.erb
<h1>Edit Cookbook</h1>
<%= render partial: 'cookbooks/partials/form' %>

app/views/cookbooks/index.html.erb
<ul>
  <% @cookbooks.each do |cookbook| %>
    <li>
        <p>
          Title: <%= cookbook.title %>
        </p>
        <p>
          Cuisine: <%= cookbook.cuisine %>
        </p>
        <p>
          Description: <%= cookbook.description %>
        </p>
    </li>
  <% end %>
</ul>

app/views/cookbooks/new.html.erb
<h1>New Cookbook</h1>
<%= render partial: 'cookbooks/partials/form' %>

app/views/cookbooks/partials/_form.html.erb
<%= form_for @cookbook do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />
  <%= f.label :cuisine %>:
  <%= f.text_field :cuisine %><br />
  <%= f.label :description %>:
  <%= f.text_field :description %>

  <% @recipes.each do |recipe| %>
    <span><%= recipe.name %></span>
    <%= check_box_tag 'cookbook[recipe_ids][]', recipe.id, recipe.in?(@cookbook.recipes.to_a) %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/cookbooks/show.html.erb
<p>Title: <%= @cookbook.title %></p>
<p>Cuisine: <%= @cookbook.cuisine %></p>
<p>Description: <%= @cookbook.description %></p>

app/views/home/index.html.erb
<h1>Hi! Welcome to the Cookbook site!</h1>

<i class='general foundicon-smiley'></i>
<i class='general foundicon-clock'></i>
<i class='general foundicon-phone'></i>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>
<%= render partial: 'ingredients/partials/form' %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
<% @ingredients.each do |ingredient| %>
  <p><%= link_to ingredient.name, ingredient %></p>
  <p>Measurement: <%= ingredient.measurement %></p>
<% end %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>
<%= render partial: 'ingredients/partials/form' %>

app/views/ingredients/partials/_form.html.erb
<%= form_for @ingredient do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :measurement %>
  <%= f.text_field :measurement %>

  <% @recipes.each do |recipe| %>
    <span><%= recipe.name %></span>
    <%= check_box_tag 'ingredient[recipe_ids][]', recipe.id, recipe.in?(@ingredient.recipes.to_a) %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name%></h1>
<p>Measurement: <%= @ingredient.measurement %></p>

<p>
  Used in:
  <ul>
    <% @ingredient.recipes.each do |recipe|%>
      <li>
        <%= recipe.name %>
      </li>
    <% end %>
  </ul>
</p>

<%= button_to 'Edit', edit_ingredient_path(@ingredient), method: 'get' %>
<%= button_to 'Delete', ingredient_path(@ingredient), method: 'delete' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" >
    <meta content="width=device-width", name="viewport">
    <title>CookbookApp</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render partial: '/layouts/partials/nav' %>
    <%= yield %>
    <script>$(document).foundation();</script>


  </body>
</html>

app/views/layouts/partials/_nav.html.erb
<nav class="top-bar">
  <div class='row'>
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "Top Bar Title", root_path %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <li class="active"><a href="#">Main Item 1</a></li>
      <li class="divider"></li>
      <li><a href="#">Main Item 2</a></li>
      <li class="divider"></li>
      <li class="has-dropdown"><a href="#">Main Item 3</a>

        <ul class="dropdown">
          <li class="has-dropdown"><a href="#">Dropdown Level 1a</a>

            <ul class="dropdown">
              <li><label>Dropdown Level 2 Label</label></li>
              <li><a href="#">Dropdown Level 2a</a></li>
              <li><a href="#">Dropdown Level 2b</a></li>
              <li class="has-dropdown"><a href="#">Dropdown Level 2c</a>

                <ul class="dropdown">
                  <li><label>Dropdown Level 3 Label</label></li>
                  <li><a href="#">Dropdown Level 3a</a></li>
                  <li><a href="#">Dropdown Level 3b</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Dropdown Level 3c</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 2d</a></li>
              <li><a href="#">Dropdown Level 2e</a></li>
              <li><a href="#">Dropdown Level 2f</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Level 1b</a></li>
          <li><a href="#">Dropdown Level 1c</a></li>
          <li class="divider"></li>
          <li><a href="#">Dropdown Level 1d</a></li>
          <li><a href="#">Dropdown Level 1e</a></li>
          <li><a href="#">Dropdown Level 1f</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider hide-for-small"></li>
      <li class="has-dropdown"><a href="#">Main Item 4</a>

        <ul class="dropdown">
          <li><label>Dropdown Level 1 Label</label></li>
          <li class="has-dropdown"><a href="#" class="">Dropdown Level 1a</a>

            <ul class="dropdown">
              <li><a href="#">Dropdown Level 2a</a></li>
              <li><a href="#">Dropdown Level 2b</a></li>
              <li class="has-dropdown"><a href="#">Dropdown Level 2c</a>

                <ul class="dropdown">
                  <li><a href="#">Dropdown Level 3a</a></li>
                  <li><a href="#">Dropdown Level 3b</a></li>
                  <li><a href="#">Dropdown Level 3c</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 2d</a></li>
              <li><a href="#">Dropdown Level 2e</a></li>
              <li><a href="#">Dropdown Level 2f</a></li>
            </ul>
          </li>
          <li><a href="#">Dropdown Level 1b</a></li>
          <li><a href="#">Dropdown Level 1c</a></li>
          <li class="divider"></li>
          <li><label>Dropdown Level 1 Label</label></li>
          <li><a href="#">Dropdown Level 1d</a></li>
          <li><a href="#">Dropdown Level 1e</a></li>
          <li><a href="#">Dropdown Level 1f</a></li>
          <li class="divider"></li>
          <li><a href="#">See all &rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li class="has-form">
        <form>
          <div class="row collapse">
            <div class="small-8 columns">
              <input type="text">
            </div>
            <div class="small-4 columns">
              <a href="#" class="alert button">Search</a>
            </div>
          </div>
        </form>
      </li>
      <li class="divider show-for-small"></li>
      <li class="has-form">
        <a class="button" href="#">Button!</a>
      </li>
    </ul>
  </section>
</div>
</nav>


<nav>
  <ul>
    <li><%= link_to 'Cookbooks', cookbooks_path %></li>
    <li><%= link_to 'New Cookbook', new_cookbook_path %></li>
    <li><%= link_to 'Recipes', recipes_path %></li>
    <li><%= link_to 'New Recipe', new_recipe_path %></li>
    <li><%= link_to 'Ingredients', ingredients_path %></li>
    <li><%= link_to 'New Ingredient', new_ingredient_path %></li>
  </ul>
</nav>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render partial: 'recipes/partials/form' %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<% @recipes.each do |recipe| %>
  <p><%= link_to recipe.name, recipe %></p>
  <p>Cooktime: <%= recipe.cook_time %></p>
  <p>Instructions: <%= recipe.instructions %></p>
  <p><img src='<%= recipe.img_url %>' ></p>
  <p><%= recipe.course %></p>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render partial: 'recipes/partials/form' %>

app/views/recipes/partials/_form.html.erb
<%= form_for @recipe do |f| %>

<!--   <% @recipe.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
   <% end %> -->

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cook_time %>
  <%= f.number_field :cook_time %>
  <%= f.label :serving_size %>
  <%= f.number_field :serving_size %>
  <%= f.label :instructions %>
  <%= f.text_field :instructions %>
  <%= f.label :img_url %>
  <%= f.text_field :img_url %>
  <%= f.label :course %>
  <%= f.text_field :course %>
  <%= f.label :cookbook_id %>
  <%= f.select :cookbook_id, Cookbook.all.map{ |cookbook| [cookbook.title, cookbook.id] } %>

<% @ingredients.each do |ingredient| %>
    <span><%= ingredient.name %></span>
    <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients.to_a) %>
    <% end %>

  <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<p>Course: <%= @recipe.course %></p>
<p>Cooktime: <%= @recipe.cook_time %></p>
<p>Instructions: <%= @recipe.instructions %></p>
<img src='<%= @recipe.img_url %>' >
<p>
<% if @recipe.cookbook.present? %>
  From Cookbook: <%= link_to @recipe.cookbook.title, @recipe.cookbook %>
  <% else %>
    Not yet published.
  <% end %>
</p>
<%= button_to 'Edit', edit_recipe_path(@recipe), method: 'get' %>
<%= button_to 'Delete', recipe_path(@recipe), method: 'delete' %>